config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :product do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:new, :show] do
    resources :payments, only: [:new]
    collection do
      get :confirmation
      get :intervention_schedueles
    end
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_one_attached :photo
  monetize :price_cents

  def labor
    if self.product.product_type == 'carrelage'
      return 35*self.surface_area
    elsif self.product.product_type == 'parquet massif'
      return 40*self.surface_area
    else
      return 30*self.surface_area
    end
  end

  def depose
    if self.floor_type == 'Carrelage'
      return 50*self.surface_area
    elsif self.floor_type == 'Parquet massif'
      return 40*self.surface_area
    elsif self.floor_type == 'Parquet stratifier'
      return 30*self.surface_area
    else
      return 0*self.surface_area
    end
  end

  def total
    return self.price = self.depose + self.labor + self.product.price_per_square_meter * self.surface_area + 50
  end

  def image_product
    if self.product.product_type == 'Carrelage'
      return 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT3-xxRrjmHG-R_mzJDld-8ExnYx9GVx66YTg&usqp=CAU'
    elsif self.product.product_type == 'Parquet massif'
      return 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSEQjKk61mtDGcVQc8sWAnYp13sMjrez2IH7RBlRDZGPldffmc8Xp9EHlmEvp4&usqp=CAc'
    else
      return 'https://www.plancheravenue.com/wp-content/uploads/2019/11/renover-parquet-stratifie-1030x687.jpg'
    end
  end



end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "Coming soon.."
    redirect_to(root_path)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :phone, :zip_code, :city, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def after_sign_in_path_for(resource)
    booking_url(Booking.last)
  end

  def after_sign_up_path_for(resource)
    booking_url(Booking.last)
  end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def index
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :authenticate_user!, except: [:new, :confirmation, :intervention_schedueles]
  def new
    @booking = Booking.new
    authorize @booking
    @step1 = params.dig(:surface_area).blank?
    @step2 = !@step1 && params.dig(:product).blank?
    @step3 = !params.dig(:product).blank?
  end

  def create
    @booking = Booking.new(booking_params)
    @product = Product.find(params[:product_id])
    @booking.product = @product
    @booking.user = current_user
    @booking.price_cents = @booking.total * 100# @booking.product.price_per_square_meter * @booking.surface_area * 100
    authorize @booking
    if @booking.save
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          name: "Réalisation d'un #{@booking.product.product_type} sur #{@booking.surface_area} m2 ",
          # images: [teddy.photo_url],
          amount: @booking.price_cents,
          currency: 'eur',
          quantity: 1
        }],
        success_url: booking_url(@booking),
        cancel_url: booking_url(@booking)
      )
      @booking.update(checkout_session_id: session.id)
      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.state == 'pending'
      @step6 = true
    else
      @step7 = true
    end
  end

  def confirmation
    build_booking_with_params
    authorize @booking
    @step4 = true
  end

  def intervention_schedueles
    build_booking_with_params
    authorize @booking
    @step5 = true
  end

  private

  def build_booking_with_params
    @booking = Booking.new
    @booking.surface_area = params[:surface_area]
    @booking.floor_type = params[:product]
    @product = Product.find_by(product_type: params[:new_product])
    @booking.product = @product
  end

  def booking_params
    params.require(:booking).permit(:surface_area, :product_id, :floor_type, :starts_at, :ends_at, :price_cents)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @booking = current_user.bookings.where(state: 'pending').find(params[:booking_id])
    authorize @booking
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_to_euro(amount)
    number_to_currency(amount, unit: '€',separator:',', delimiter:' ', format:'%n %u')
  end
end

app/views/bookings/confirmation.html.erb
<%= render 'shared/stepper'%>
<div class="container align-self-center justify-content-center">
  <div class="row">
    <div class="  card-product card-product-offset w-100 m-3">
      <img src="<%=@booking.image_product%>"  alt="your floor" >
      <div class='w-100 m-3 p-3'>
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between font-weight-bold h4">
            <div> Total devis</div>
            <div> <%= number_to_euro(@booking.total)%></div>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <div> Coût d'achat</div>
            <div><%= number_to_euro(@booking.product.price_per_square_meter * @booking.surface_area) %></div>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <div> Main d'oeuvre</div>
            <div><%=number_to_euro(@booking.depose + @booking.labor)%></div>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <div> Livraison</div>
            <div> <%=number_to_euro(50)%> </div>
          </li>
        </ul>
        <div class = 'text-right w-50 mx-auto mt-3'>
          <%= link_to "Voir les disponibilités", intervention_schedueles_bookings_path(surface_area: params[:surface_area],product: params[:product], new_product: params[:new_product]), class: "example_f"  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Selectionez vos dates</h2>

    <%= simple_form_for :search, method: "get" do |f| %>
      <%= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= t.input :starts_at, input_html: { id: "range_start" } %>
      <%= t.input :ends_at, input_html: { id: "range_end" } %>
      <%= f.button :submit, "Valider", class: "button-invers m-2 " %>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<h1>test</h1>

app/views/bookings/intervention_schedueles.html.erb
<%= render 'shared/stepper' %>
<div class="background_calendar d-flex align-self-start justify-content-center align-items-center">

 <div class="form" style="box-shadow: 0 0 10px rgba(0, 0, 0, 0.5)">
  <%# form-wrapper text-justify text-center rgb(120, 121, 120) bg-light rounded p-3 m-3 transi Larger shadow %>
    <h2 class="title">Sélectionnez vos disponibilités</h2>

    <%= simple_form_for [@product, @booking] do |f| %>
      <%= f.input :starts_at,
                  label: false,
                  placeholder: 'Débute le',
                  as: :string,
                  required: false,
                  input_html: { id: "range_start", class: "input-value" } %>
      <%= f.input :ends_at,
                  label: false,
                  placeholder: 'Finit le',
                  as: :string,
                  required: false,
                  input_html: { id: "range_end", class: "input-value" } %>
      <%= f.input :surface_area, as: :hidden %>
      <%= f.input :product_id, as: :hidden %>
      <%= f.input :floor_type, as: :hidden %>
      <div class="d-flex justify-content-center">
        <%= f.submit 'Valider', class: "example_f justify-content"%>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<%= render 'shared/stepper', locals: {:step => @step1} %>
<div class="container-products mt-4 fix-footer">
  <% if @step1 %>
    <%= render 'shared/booking-step1' %>
  <% end %>
  <% if @step2 %>
    <%= render 'shared/booking-step2' %>
  <% end %>
  <% if @step3 %>
    <%= render 'shared/booking-step3' %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<%= render 'shared/stepper' %>
<% if @booking.state == 'pending' %>
  <div class=" d-flex align-self-start justify-content-center">
    <div class="card-product">
      <img src="<%=@booking.image_product%>" alt="your floor" >
      <div class="card-product-infos w-100 m-3">
        <h1 class='title'>Votre récapitulatif</h1>
        <p>En espérant que notre service vous convienne <strong><%= @booking.user.name%> </strong>.</p>
        <p>Notre professionnel posera du <strong><%=@booking.product.product_type%></strong></p>
        <p>Vos travaux sont prévus du: </p>
        <p> <strong><%= @booking.starts_at.strftime("%d/%m/%Y")%></strong> au <strong><%= @booking.ends_at.strftime("%d/%m/%Y")%></strong></p>
        <div class="total_pay mt-3">
          <h2 >Coût total</h2>
          <h2 class = "mt-3"><strong><%= number_to_euro(@booking.total) %></strong></h2>
            <div class="  d-flex justify-content-center mt-3">
              <a class="pay button_cont" id="pay" rel="nofollow"><span>Payer</span></a>
            </div>
            <script src="https://js.stripe.com/v3/"></script>
            <script>
              const paymentButton = document.getElementById('pay');
              paymentButton.addEventListener('click', () => {
                const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
                stripe.redirectToCheckout({
                  sessionId: '<%= @booking.checkout_session_id %>'
                });
              });
            </script>
<% else %>
  <div class=" d-flex align-self-start justify-content-center fix-footer ">
    <div class="card-product ">
    <img src="<%=@booking.image_product%>" alt="your floor" >
    <div class="card-product-infos w-100 m-3">
        <h3 class="title">Merci pour votre confiance !</h3>
        <p>En espérant que votre projet se réalise sans encombre.</p>
        <p>Notre professionnel du <strong><%=@booking.product.product_type%></strong> sera bientôt au courant de votre demande</p>
          <h1 style="font-family: 'Cormorant Garamond', serif">À bientôt sur <strong class="title my-3">Find & Trust</strong></h1>
          <div class="d-flex justify-content-center mt-3 example_f">
            <a href="/" id="retour">Retour</a>
          </div>
        </div>
    </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrustAndFind</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- TODO: Fonts needs to load via sprockets (in app/stylesheet/config/_fonts.scss)  -->
    <link href="https://fonts.googleapis.com/css2?family=Halant&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Maven+Pro&display=swap" rel="stylesheet">
    <%= favicon_link_tag %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner fix-footer">
  <h1>Find & Trust</h1>
  <h2 class="punchline">Find Faster, Trust More</h2>
   <%= link_to 'Aller plus loin', new_booking_path, class: 'button' %>
</div>
<!-- <h2 class="question mb-3">Comment ça marche ?</h2>
<div class="container mb-3">
  <div class="row">
    <div class="col-12 col-lg-4">
      <div class="card-step shadow p-3 bg-white rounded">
        <h3><i class="fas fa-search"></i></h3>
        <h4>On trie pour vous</h4>
        <p>
          Questionnaire simple, 3 questions essentielles, aucune complexité.
          Cela nous permettra de comprendre votre projet.
        </p>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="card-step shadow p-3 bg-white rounded">
        <h3><i class="fas fa-truck"></i></h3>
        <h4>Puis on trouve le bon service</h4>
        <p>
          On trouve les services adaptés à vos réponses, traçant alors le meilleur chemin entre vous et nos artisants.
        </p>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="card-step shadow p-3 bg-white rounded ">
        <h3><i class="fas fa-money-check"></i></h3>
        <h4>Paiement</h4>
        <p>
          Paiement après la création de votre projet. Vous saurez alors ce que vous payer exactement grâce à notre récapitulatif détaillé.
        </p>
      </div>
    </div>

  </div>
</div> -->
  <!-- <div class="illustration d-flex col-12 shadow-lg p-2 mb-5 bg-white rounded text-align-center">
    <%= image_tag "https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2020/02/08/node_707104/45321071/public/2020/02/08/B9722503364Z.1_20200208100036_000%2BG7JFFEQBD.1-0.jpg?itok=x08RiM8r1581152443", alt: "alttext", class: "img-illu" %>
    <p class="description ml-3 mr-3">
      Voici Patrick, c'est un des artisants de Trust & Find, bien connu de nos services. Il a sa propre compagnie et reste un passionné.
      Trust & Find lui donne l'opportunité d'agrandir son réseau de client.
      Nos artisants comme Patrick sont des personnes de confiance et sont là pour vos projets.
      Faites leur confiance, faites nous confiance.
    </p>
  </div> -->

app/views/payments/new.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col">
      <h1>Checkout summary</h1>
      <p>Purchase of <strong><%= @booking.product.product_type %></strong> for <strong><%= humanized_money_with_symbol @booking.price %></strong></p>
      <button id="pay" class="btn btn-primary">Pay</button>
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @booking.checkout_session_id %>'
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/shared/_booking-step1.html.erb
<div class="container text-center">

  <h1 class="text-center mb-4 title">Quelle est la surface à rénover en m² ?</h1>
  <div class="col-xs-2 form-inline justify-content-center">
    <div>
      <form class="form-inline ">
        <div class="form-group mb-2">
          <%= simple_form_for :bookings, url:     new_booking_path,
                                         method: :get do |f| %>
            <%= f.input :surface_area, label: false,
                                       input_html: { name: 'surface_area', value: params[:surface_area], class: "input-value" } %>
            <%= f.submit "Valider", class: 'example_f ml-4 text-center' %>
          <% end %>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/shared/_booking-step2.html.erb
<h1 class="text-center mt-4 mb-4 title">Quel est le support existant?</h1>
  <div class="container-fluid">
    <div class="row pl-0 pr-0">
      <div class="col-12 col-lg-3 ">
        <div class="card-floor transi <%= params[:product] == 'Carrelage' ? 'selected': '' %>">
          <%= link_to new_booking_path(surface_area: params[:surface_area], product: 'Carrelage') do %>
            <%= image_tag "https://i.pinimg.com/originals/88/ff/6e/88ff6e93b081465f9ec21d6bd3f11305.jpg", alt: "Le Wagon", width: 200 %>
            <h3 id="carrelage" class="card-title">Carrelage</h3>
          <% end %>
        </div>
      </div>
      <div class="col-12 col-lg-3">
        <div class="card-floor transi <%= params[:product] == 'plancher massif' ? 'selected': '' %>">
          <%= link_to new_booking_path(surface_area: params[:surface_area], product: 'plancher massif') do  %>
            <%= image_tag "https://www.parqueteriefrancaise.fr/modules/ph_simpleblog/featured/36-featured.jpg", alt: "Le Wagon", width: 200 %>
            <h3 class="card-title">Plancher massif</h3>
          <% end %>
        </div>
      </div>
      <div class="col-12 col-lg-3">
        <div class="card-floor transi <%= params[:product] == 'parquet stratifé' ? 'selected': '' %>">
          <%= link_to new_booking_path(surface_area: params[:surface_area], product: 'parquet stratifé') do  %>
            <%= image_tag "https://static.comment-economiser.fr/documents/images/2018/02/gondolement-lames-guide-comment-nettoyer-sol-stratifie.jpg", alt: "Le Wagon", width: 200 %>
            <h3 class="card-title">Parquet stratifé</h3>
          <% end %>
        </div>
      </div>
      <div class="col-12 col-lg-3">
        <div class="card-floor transi <%= params[:product] == 'brut' ? 'selected': '' %>">
          <%= link_to new_booking_path(surface_area: params[:surface_area], product: 'brut') do  %>
            <%= image_tag "https://media1.forumconstruire.com/photo/large/140179.jpg", alt: "Le Wagon", width: 200 %>
            <h3 id="brut" class="card-title">Brut</h3
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_booking-step3.html.erb
<h1 class="text-center mb-4 mt-4 title">Que voulez-vous à la place?</h1>
<div class="container mb-0 " id = "step3">
  <div class="row pl-0 pr-0 mb-4">
    <div class="col-12 col-lg-4 ">
      <div class="card-floor card-mini transi">
        <%= link_to confirmation_bookings_path( surface_area: params[:surface_area],product: params[:product], new_product: 'Carrelage') do  %>
          <div style="color: black">
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT3-xxRrjmHG-R_mzJDld-8ExnYx9GVx66YTg&usqp=CAU", alt: "Le Wagon", width: 200 %>
            <h3 class="little-title" id="little-carrelage"><%=  Product.first.product_type %></h3>
            <!-- <hr color= #dbd4d4> -->
            <h6 class="text-center para">Le carrelage répondra à vos besoins</h6>
            <h3 class='card-price'>23<span class='currency'>€</span><span class='units'>/m2</span></h3>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-lg-4 ">
      <div class="card-floor card-mini transi">
        <%= link_to confirmation_bookings_path( surface_area: params[:surface_area],product: params[:product], new_product: 'Parquet massif')  do  %>
          <div style="color: black">
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSEQjKk61mtDGcVQc8sWAnYp13sMjrez2IH7RBlRDZGPldffmc8Xp9EHlmEvp4&usqp=CAc", alt: "Le Wagon", width: 200 %>
            <h3 class="little-title"><%= Product.second.product_type %></h3>
            <!-- <hr color= #dbd4d4> -->
            <h6 class="text-center para">Matériaux chaleureux</h6>
            <h3 class='card-price'>90<span class='currency'>€</span><span class='units'>/m2</span></h3>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-lg-4 ">
      <div class="card-floor card-mini transi">
        <%= link_to confirmation_bookings_path( surface_area: params[:surface_area],product: params[:product], new_product: 'Parquet flottant') do  %>
          <div style="color: black">
            <%= image_tag "https://www.plancheravenue.com/wp-content/uploads/2019/11/renover-parquet-stratifie-1030x687.jpg", alt: "Le Wagon", width: 200 %>
            <h3 class="little-title"><%= Product.last.product_type %></h3>
            <!-- <hr color= #dbd4d4> -->
            <h6 class="text-center para">Sans bruit et agréable</h6>
            <h3 class='card-price'>20<span class='currency'>€</span><span class='units'>/m2</span></h3>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-blue alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    About us
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Privacy Policy
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= 'bg-transparent border-0 position-absolute' if current_page?(root_path) %> ">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "good_logo_3_2.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "valerie.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>